version: '3.1'

services:
  nestjs-app:
    build:
      context: .
    env_file: .env
    environment:
      DB_HOST: db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - db
    restart: always

  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init/db.sql:/docker-entrypoint-initdb.d/db.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
